"$schema" = 'https://starship.rs/config-schema.json'

palette = "catppuccin_macchiato"
# Inserts a blank line between shell prompts
add_newline = true

# Use custom format
format = '''
[ ](blue)$directory$fill $rust$package$python$git_branch$git_status
[  ](blue) '''

# Starship modules
# [character]
# Note the use of Catppuccin color 'peach'
# success_symbol = "[[󰄛 ](green) ❯](peach)"
# error_symbol = "[[󰄛 ](red) ❯](peach)"
# vimcmd_symbol = "[󰄛 ❮](subtext1)" # For use with zsh-vi-mode

[package]
disabled = true

[python]
symbol = " "
style = "yellow"
format='[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
version_format = '${major}.${minor}'

[directory]
read_only = " 󰌾"
style = "blue"
format = '[$path]($style)[$read_only]($read_only_style) '
truncation_length = 3
truncation_symbol = " "
home_symbol = " "

[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style) '
style = "pink"
symbol = " "

[git_commit]
tag_symbol = '  '

[git_status]
format = '([\($all_status$ahead_behind\)]($style) )'
style = "text"
conflicted = " ${count}"
ahead = '󰳢 ${count}'
diverged = '󱡷 ${ahead_count}󰁅 ${behind_count}'
behind = '󰁅 ${count}'
deleted = "󰆴 ${count}"
renamed = " ${count}"
untracked = " ${count}"
modified = " ${count}"
staged = " ${count}"

[fill]
symbol = ' '
style = 'bold green'

# just in case

[docker_context]
symbol = " "
[rlang]
symbol = "󰟔 "

[ruby]
symbol = " "

[rust]
symbol = "󱘗 "
style = "red" 
version_format = '${major}.${minor}'
format='[${symbol}(${version})]($style) '

[c]
symbol = " "

[cpp]
symbol = " "

[cmake]
symbol = " "

[elixir]
symbol = " "

[fortran]
symbol = " "

[golang]
symbol = " "

[hostname]
ssh_symbol = " "

[julia]
symbol = " "

[lua]
symbol = " "

[memory_usage]
symbol = "󰍛 "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[palettes.catppuccin_macchiato]
rosewater = "#f4dbd6"
flamingo = "#f0c6c6"
pink = "#f5bde6"
mauve = "#c6a0f6"
red = "#ed8796"
maroon = "#ee99a0"
peach = "#f5a97f"
yellow = "#eed49f"
green = "#a6da95"
teal = "#8bd5ca"
sky = "#91d7e3"
sapphire = "#7dc4e4"
blue = "#8aadf4"
lavender = "#b7bdf8"
text = "#cad3f5"
subtext1 = "#b8c0e0"
subtext0 = "#a5adcb"
overlay2 = "#939ab7"
overlay1 = "#8087a2"
overlay0 = "#6e738d"
surface2 = "#5b6078"
surface1 = "#494d64"
surface0 = "#363a4f"
base = "#24273a"
mantle = "#1e2030"
crust = "#181926"

